"""Bootstrap Superuser CLI core — Phase 6.5-a, ADR 0018.

Creates (or rotates the password of) the single install-level Superuser
"Wolf". Properties per ADR 0018 §"Decision: bootstrap Superuser":

  - Username FIXED: ``Wolf`` (display name). The login endpoint accepts
    the literal username "Wolf"; internally the account is keyed by the
    reserved email ``wolf@wolf.local`` (the User model's unique login
    column is email — the reserved address is non-routable by design).
  - Password: 32-char random, autogenerated, printed ONCE to stdout.
    Never logged, never stored in plaintext, never shown again.
  - Zero organization memberships at creation (install-level identity;
    data access requires an org Admin's explicit consent — ADR 0018
    org-consent gate).
  - Cannot be deleted or renamed; recovery is THIS tool's --rotate-password.

Invocation: ONLY via the shell wrapper (`deploy/bin/bootstrap_superuser`,
shipped as /usr/bin/bootstrap_superuser in the wolf-server .deb). Direct
``python -m wolf_server.bootstrap.superuser`` invocation is rejected via
the WOLF_WRAPPER_VERSION env check (shell-wrapper-required pattern).

Usage (via the wrapper):
  bootstrap_superuser                    # create if absent (idempotent)
  bootstrap_superuser --rotate-password  # new password for existing Wolf

Exit codes:
  0 — created / rotated / already-exists (nothing to do)
  2 — invoked without the wrapper
  3 — --rotate-password but no Superuser exists yet
"""

import argparse
import asyncio
import os
import secrets
import sys
import uuid
from datetime import UTC, datetime

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

# Import models so SQLAlchemy metadata is fully populated.
import wolf_server.audit.models  # noqa: F401
import wolf_server.organization.models  # noqa: F401
import wolf_server.wazuh.models  # noqa: F401
from wolf_server.audit.log import write_event
from wolf_server.auth.local import hash_password
from wolf_server.config import get_settings
from wolf_server.database import Base
from wolf_server.organization.models import User

logger = structlog.get_logger(__name__)

# Fixed identity per ADR 0018. The username is what operators type at
# login; the reserved email is the internal unique key (non-routable,
# .local TLD is reserved by RFC 6762 so it can never collide with a
# real operator address).
SUPERUSER_USERNAME = "Wolf"
SUPERUSER_EMAIL = "wolf@wolf.local"

# 24 random bytes -> 32 base64url chars. Meets the ADR's "32+ char
# random" requirement with ~144 bits of entropy.
_PASSWORD_BYTES = 24


def generate_password() -> str:
    """Return a fresh 32-character URL-safe random password."""
    return secrets.token_urlsafe(_PASSWORD_BYTES)


def _require_wrapper() -> None:
    """Reject direct invocation — the shell wrapper is the only path.

    The wrapper sets WOLF_WRAPPER_VERSION; nothing else does. See the
    shell-wrapper-required pattern: audit attribution, env preflight,
    and permission gating all live in the wrapper.
    """
    if not os.environ.get("WOLF_WRAPPER_VERSION"):
        sys.stderr.write(
            "ERROR: this tool must be invoked via its shell wrapper, not directly.\n"
            "  Installed:  sudo /usr/bin/bootstrap_superuser\n"
            "  Dev:        ./deploy/bin/bootstrap_superuser\n"
        )
        raise SystemExit(2)


async def _ensure_schema(database_url: str) -> None:
    """For SQLite dev DBs, create tables on the fly. Postgres uses Alembic."""
    if "sqlite" not in database_url:
        return
    engine = create_async_engine(database_url, echo=False)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    await engine.dispose()


def _print_password_banner(password: str, *, rotated: bool) -> None:
    """Print the one-time password banner to stdout.

    This is the ONLY place the password is ever emitted. It is not
    logged, not stored, not returned. The operator stores it themselves
    (e.g. a password manager) — ADR 0018 Round 1 operator decision:
    stdout-only delivery.
    """
    action = "rotated" if rotated else "created"
    sys.stdout.write(
        "\n"
        "  ──────────────────────────────────────────────────────────────\n"
        f"  Superuser '{SUPERUSER_USERNAME}' {action}.\n"
        "\n"
        f"      username : {SUPERUSER_USERNAME}\n"
        f"      password : {password}\n"
        "\n"
        "  This password is shown ONCE and is not stored anywhere.\n"
        "  Save it in your password manager NOW.\n"
        "  Lost it? Re-run with --rotate-password (operator-on-host).\n"
        "  If this ran inside a captured session (e.g. apt's term.log),\n"
        "  rotate afterwards so no log retains a live credential.\n"
        "  ──────────────────────────────────────────────────────────────\n"
        "\n"
    )


async def ensure_superuser(*, rotate_password: bool = False) -> int:
    """Create the Superuser if absent, or rotate its password.

    Returns the process exit code. Prints the password banner to stdout
    on create/rotate; prints a no-op notice when the Superuser already
    exists and no rotation was requested.
    """
    settings = get_settings()
    await _ensure_schema(settings.database_url)

    engine = create_async_engine(settings.database_url, echo=False)
    factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    try:
        async with factory() as db:
            existing = await db.scalar(
                select(User).where(User.is_superuser.is_(True), User.email == SUPERUSER_EMAIL)
            )

            if rotate_password:
                if existing is None:
                    sys.stderr.write(
                        "ERROR: no Superuser exists yet — run without "
                        "--rotate-password to create it first.\n"
                    )
                    return 3
                password = generate_password()
                existing.hashed_password = hash_password(password)
                existing.is_active = True
                existing.updated_at = datetime.now(UTC)
                await write_event(
                    db,
                    event_type="superuser.password.rotated",
                    event_data={"username": SUPERUSER_USERNAME, "via": "bootstrap_superuser"},
                    user_id=existing.id,
                )
                await db.commit()
                _print_password_banner(password, rotated=True)
                logger.info("superuser_password_rotated", user_id=str(existing.id))
                return 0

            if existing is not None:
                sys.stdout.write(
                    f"Superuser '{SUPERUSER_USERNAME}' already exists — nothing to do.\n"
                    "  (Use --rotate-password to generate a new password.)\n"
                )
                return 0

            password = generate_password()
            user = User(
                id=uuid.uuid4(),
                email=SUPERUSER_EMAIL,
                display_name=SUPERUSER_USERNAME,
                hashed_password=hash_password(password),
                is_active=True,
                is_superuser=True,
                created_at=datetime.now(UTC),
                updated_at=datetime.now(UTC),
            )
            db.add(user)
            await db.flush()
            await write_event(
                db,
                event_type="superuser.bootstrap.created",
                event_data={"username": SUPERUSER_USERNAME, "via": "bootstrap_superuser"},
                user_id=user.id,
            )
            await db.commit()
            _print_password_banner(password, rotated=False)
            logger.info("superuser_created", user_id=str(user.id))
            return 0
    finally:
        await engine.dispose()


def _parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--rotate-password",
        action="store_true",
        help=(
            "Generate a new password for the existing Superuser and print "
            "it once. The recovery path when the Wolf password is lost — "
            "operator-on-host only, audit-logged."
        ),
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    _require_wrapper()
    args = _parse_args(argv if argv is not None else sys.argv[1:])
    return asyncio.run(ensure_superuser(rotate_password=args.rotate_password))


if __name__ == "__main__":
    raise SystemExit(main())
