"""Render the postgresql.conf and pg_hba.conf wolf-database uses.

Wolf doesn't tune Postgres aggressively — the defaults Postgres 18
ships with are reasonable for Wolf's mixed workload (low-volume
audit + organization chats + pgvector retrieval). We override only the
settings we genuinely need:

* `listen_addresses` — wolf-database binds loopback only by default.
  Distributed deployments override via env to bind a LAN address;
  the mTLS substrate (Phase 5.6) means we don't need to fear LAN
  exposure.
* `unix_socket_directories` — points at our Wolf-owned socket dir
  rather than the system default (`/var/run/postgresql`), so we
  don't collide with another Postgres instance running on the same
  host (a real concern during the migration period when operators
  may have system Postgres alongside wolf-database).
* `shared_preload_libraries = 'vector'` — pgvector requires this
  load at server start; the extension can't be installed otherwise.
* `port` — defaults to 5432 (Postgres default); operators on a host
  that already has a Postgres can override.

Everything else (memory tuning, WAL config, autovacuum) we leave to
the upstream defaults. If Wolf ever needs aggressive tuning we'll
add per-knob settings here as a focused change rather than ship a
bulk "wolf-tuned" config that hides what it's doing.

`pg_hba.conf` is rendered from a small allowlist of (host, db,
user, method) tuples. Default is loopback + Unix socket only with
SCRAM-SHA-256 password auth. Distributed deployments will add a
TLS-required host entry in Phase 5.8 once the wolf-database leaf
cert is wired up.
"""

from __future__ import annotations

import urllib.parse
from dataclasses import dataclass, field

from wolf_database.layout import DB_NAME_DEFAULT, DB_USER_DEFAULT, DatabaseLayout

DEFAULT_PORT = 5432


@dataclass(frozen=True)
class PostgresqlConfOptions:
    """Tunable options for the postgresql.conf wolf-database renders.

    Defaults are documented at the module top. Override individual
    fields when constructing for tests or for an unusual deployment.
    """

    listen_addresses: str = "localhost"
    port: int = DEFAULT_PORT
    # shared_preload_libraries is hardcoded to 'vector' — wolf-server
    # needs pgvector and the extension MUST be loaded at startup, not
    # at CREATE EXTENSION time. Not exposed as a field because it's a
    # hard requirement, not a tunable.

    # Logging. Default sends everything to stderr; systemd captures
    # it into journald in production, and the dev CLI prints it
    # inline. No separate log file.
    log_destination: str = "stderr"
    logging_collector: bool = False

    def render(self, layout: DatabaseLayout) -> str:
        """Return the postgresql.conf body as a string."""
        return (
            "# postgresql.conf — managed by wolf-database (Phase 5.7).\n"
            "# Do not edit by hand; this file is regenerated by\n"
            "# `wolf-database init` and `wolf-database reconfigure`.\n"
            "#\n"
            "# To customise, set the corresponding WOLF_DATABASE_* env\n"
            "# var (e.g. WOLF_DATABASE_LISTEN_ADDRESSES) and re-run\n"
            "# `wolf-database reconfigure`.\n"
            "\n"
            f"data_directory = '{layout.data_dir}'\n"
            f"hba_file = '{layout.pg_hba_conf_path}'\n"
            f"listen_addresses = '{self.listen_addresses}'\n"
            f"port = {self.port}\n"
            f"unix_socket_directories = '{layout.socket_dir}'\n"
            "shared_preload_libraries = 'vector'\n"
            f"log_destination = '{self.log_destination}'\n"
            f"logging_collector = {'on' if self.logging_collector else 'off'}\n"
        )


@dataclass(frozen=True)
class PgHbaRule:
    """One row of the pg_hba.conf access-control table.

    Fields map 1:1 to Postgres's pg_hba.conf format:
    https://www.postgresql.org/docs/18/auth-pg-hba-conf.html
    """

    connection_type: str  # `local`, `host`, `hostssl`, `hostnossl`
    database: str
    user: str
    address: str | None
    method: str

    def render(self) -> str:
        parts = [self.connection_type, self.database, self.user]
        if self.address is not None:
            parts.append(self.address)
        parts.append(self.method)
        return " ".join(parts)


@dataclass(frozen=True)
class PgHbaOptions:
    """Configuration for the pg_hba.conf wolf-database renders.

    The default ruleset is "loopback + Unix socket, SCRAM-SHA-256."
    Distributed deployments add a `hostssl` rule via
    `extra_rules=...` to allow LAN-reachable mTLS connections; that
    wiring lands in Phase 5.8 when the wolf-database cert leaf is
    added to `wolf-cert init`.
    """

    db: str = DB_NAME_DEFAULT
    user: str = DB_USER_DEFAULT
    extra_rules: tuple[PgHbaRule, ...] = field(default_factory=tuple)

    def render(self) -> str:
        rules = [
            # Local socket: peer auth matches initdb's --auth-local peer.
            # OS-user identity is the auth. wolf-server running as the
            # `wolf-database` OS user connects this way in production;
            # in dev the operator's OS user is superuser so the local
            # socket is the convenient admin channel.
            PgHbaRule(
                connection_type="local",
                database="all",
                user="all",
                address=None,
                method="peer",
            ),
            # TCP loopback: scram-sha-256 with a password. This is how
            # wolf-server actually connects (via DATABASE_URL with
            # asyncpg over TCP — asyncpg doesn't support Unix sockets
            # cleanly across all distros).
            PgHbaRule(
                connection_type="host",
                database=self.db,
                user=self.user,
                address="127.0.0.1/32",
                method="scram-sha-256",
            ),
            PgHbaRule(
                connection_type="host",
                database=self.db,
                user=self.user,
                address="::1/128",
                method="scram-sha-256",
            ),
            *self.extra_rules,
        ]
        body = "\n".join(rule.render() for rule in rules)
        return (
            "# pg_hba.conf — managed by wolf-database (Phase 5.7).\n"
            "# Do not edit by hand; regenerated by\n"
            "# `wolf-database init` and `wolf-database reconfigure`.\n"
            "#\n"
            "# TYPE  DATABASE  USER  ADDRESS  METHOD\n"
            f"{body}\n"
        )


def write_config(
    layout: DatabaseLayout,
    *,
    pg_options: PostgresqlConfOptions | None = None,
    hba_options: PgHbaOptions | None = None,
) -> None:
    """Write postgresql.conf + pg_hba.conf into `layout.config_dir`.

    Creates the config directory if it doesn't exist. Files are
    written with mode 0640 (Postgres rejects pg_hba/postgresql world-
    readable in some configurations; 0640 is restrictive enough for
    config but allows the postgres group to read).
    """
    pg_opts = pg_options or PostgresqlConfOptions()
    hba_opts = hba_options or PgHbaOptions()

    layout.config_dir.mkdir(parents=True, exist_ok=True)

    pg_conf = layout.postgresql_conf_path
    pg_conf.write_text(pg_opts.render(layout))
    pg_conf.chmod(0o640)

    hba_conf = layout.pg_hba_conf_path
    hba_conf.write_text(hba_opts.render())
    hba_conf.chmod(0o640)


def connection_url(
    layout: DatabaseLayout,
    *,
    user: str = DB_USER_DEFAULT,
    db: str = DB_NAME_DEFAULT,
    password: str | None = None,
    via_socket: bool = True,
    port: int = DEFAULT_PORT,
) -> str:
    """Build a SQLAlchemy connection URL for wolf-server to use.

    Two modes:
      * via_socket=True (default for all-in-one): connects via Unix
        domain socket under `layout.socket_dir`. No password needed
        if pg_hba allows `local trust`, but we default to scram so
        a password IS needed.
      * via_socket=False: TCP to localhost:port (or whatever the
        operator overrides). The wolf-server's existing async DB
        layer wants asyncpg over TCP, so this is the form wolf-server
        will actually use for the foreseeable future.

    Returned URL is the `postgresql+asyncpg://...` shape SQLAlchemy
    expects (matches wolf-server's existing DATABASE_URL convention).
    """
    auth = ""
    if password is not None:
        # urlencode handles special chars; the password may have been
        # rolled with random bytes.
        auth = f":{urllib.parse.quote(password, safe='')}"

    if via_socket:
        # SQLAlchemy quotes a socket path with `host=` query param.
        socket = urllib.parse.quote(str(layout.socket_dir), safe="")
        return f"postgresql+asyncpg://{user}{auth}@/{db}?host={socket}"
    return f"postgresql+asyncpg://{user}{auth}@localhost:{port}/{db}"
